#生产环境
#开发环境
spring:
  datasource:
    druid:
      # 数据源基本配置
      url: jdbc:mysql://172.17.0.1:3306/ebe_base?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
      username: root
      password: root
      initial-size: 3
      min-idle: 1
      max-active: 10
      test-on-borrow: true
      max-wait: 10000
      driver-class-name: com.mysql.cj.jdbc.Driver
      filters : stat, wall, slf4j
  redis:
    # Redis数据库索引（默认为 0）
    database: 0
    # Redis服务器地址
    host: 172.17.0.4
    # Redis服务器连接端口
    port: 6379
    # Redis 密码
    password:
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 8
        # 连接池中的最大空闲连接
        max-idle: 500
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 2000
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 10000
    # 连接超时时间（毫秒）
    timeout: 5000
  #开启缓存
  thymeleaf:
    cache: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  #  开启热部署
  devtools:
    restart:
      enabled: true

